
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://172.16.165.238:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    timeout: 300000
    retries: 10

server:
  port: 8062