
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://172.16.165.237:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 60000

server:
  port: 8062