
dubbo:
  application:
    name: dubbo-provider
    shutwait: 300000      # 优雅停机时间
  registry:
    address: zookeeper://172.16.165.238:2181
    protocol: zookeeper
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
    check: true
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: register
  consumer:
    timeout: 300000
    retries: 10

server:
  port: 8065